src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: "email", message: "Cet email existe déjà")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\Email(message: "Veuillez renseigner une adresse mail valide.")]
    #[Assert\NotBlank(message: "Veuillez renseigner une adresse mail.")]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    #[Assert\Length(min: 6, minMessage: "Le mot de passe doit faire au moins 6 caractères.")]
    #[Assert\NotBlank(message: "Veuillez entrer un mot de passe.")]
    private $password;

    #[Assert\Length(min: 6, minMessage: "Le mot de passe doit faire au moins 6 caractères.")]
    private $newPassword;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner votre prénom.")]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner votre nom.")]
    private $lastname;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Question::class, orphanRemoval: true)]
    private $questions;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private $comments;

    #[ORM\Column(type: 'string', length: 255)]
    private $image;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Vote::class, orphanRemoval: true)]
    private $votes;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getNewPassword(): ?string
    {
        return $this->newPassword;
    }

    public function setNewPassword(string $newPassword): self
    {
        $this->newPassword = $newPassword;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname() : ?string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setAuthor($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getAuthor() === $this) {
                $question->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes[] = $vote;
            $vote->setAuthor($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): self
    {
        if ($this->votes->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getAuthor() === $this) {
                $vote->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        /**
         * @var User
         */

        $user = $builder->getData();
        $builder
            ->add('email', EmailType::class, ['label' => '*Email'])
            ->add('firstname', TextType::class, ['label' => '*Prénom'])
            ->add('lastname', TextType::class, ['label' => '*Nom'])
            ->add('imageFile', FileType::class, [
                'label' => '*Image',
                // 'required' => $user?->getImage() ? false : true,
                'required' => $options['new_user'],
                'mapped' => false,
                'constraints' => [
                    new Image([
                        'mimeTypesMessage' => 'Veuillez uploader une image.',
                        'maxSize' => '1M',
                        'maxSizeMessage' => 'Votre image fait {{ size }} {{ suffix }}. La limite est de {{ limit }}'
                    ])
            ]
            ])
            ->add('password', PasswordType::class, ['label' => '*Mot de passe'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'new_user' => true
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Service\UploaderPicture;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;


#[Route('user')]
class UserController extends AbstractController
{


    #[Route('/', name: 'current_user')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function currentUserProfile(Request $request, UserPasswordHasherInterface $passwordHasher, EntityManagerInterface $em, UploaderPicture $uploaderPicture): Response
    {

        /**
         * @var User
         */

        $user = $this->getUser();
        $userFormProfile = $this->createForm(UserType::class, $user, ['new_user' => false]);
        $userFormProfile->remove('password');
        $userFormProfile->add('newPassword', PasswordType::class, [
            'label' => 'Nouveau mot de passe',
            'required' => false
        ]);
        $userFormProfile->handleRequest($request);

        if($userFormProfile->isSubmitted() && $userFormProfile->isValid()) {
            $newPassword = $user->getNewPassword();
            if($newPassword) {
                $hash = $passwordHasher->hashPassword($user, $newPassword);
                $user->setPassword($hash);
            }

            $newImage = $userFormProfile->get('imageFile')->getData();
            if ($newImage) {
                $user->setImage($uploaderPicture->uploadProfileImage($newImage, $user->getImage()));
            }

            $em->flush();
            $this->addFlash('success', 'Modification du mot de passe enregistrée');
        }

        return $this->render('user/index.html.twig', [
            'form' => $userFormProfile->createView()
        ]);
    }

    #[Route('/questions', name: 'show_questions')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function showQuestions() : Response {
        return $this->render('user/show_questions.html.twig');
    }

    #[Route('/comments', name: 'show_comments')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function showComments() : Response {
        return $this->render('user/show_comments.html.twig');
    }

    #[Route('/{id}', name: 'user')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function userProfile(User $user): Response
    {

        $currentUser= $this->getUser();

        if($user === $currentUser) {
            return $this-> redirectToRoute('current_user');
        }
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ma page de profil{% endblock %}

{% block body %}
    <div class="block">
        <h2 class="pb-30">Page de profil</h2>
        {{ form_start(form) }}
            {{ form_rest(form) }}
            <button class="btn btn-primary">Sauvegarder</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{ user.fullname }}
{% endblock title %}

{% block body %}
    <div class="block mb-20">
        <h2 class="pb-30">{{ user.fullname }}</h2>
        <div class="d-flex flex-row-nowrap">
            <img src="{{ user.image }}" alt="Profile picture" class="mr-10 profile-picture">
            <ul>
                <li class="mb-10">
                    <strong class="mr-10">Prénom: </strong>{{ user.firstname }}
                </li>
                <li class="mb-10">
                    <strong class="mr-10">Nom: </strong>{{ user.lastname }}
                </li>
                <li class="mb-10">
                    <strong class="mr-10">Email: </strong>{{ user.email }}
                </li>
            </ul>
        </div>
    </div>

    <div class="block mb-20">
        <h3 class="pb-30">Ses questions</h3>
        <ul>
            {% for question in user.questions %}
                <a href="{{ path('question_show', {id: question.id}) }}">
                    <li class="pb-30">{{ question.title }}</li>
                </a>
            {% endfor %}
        </ul>
    </div>

    <div class="block mb-20">
        <h3 class="pb-30">Ses réponses</h3>
        <ul>
            {% for comment in user.comments %}
                    <li class="pb-30">
                        {{ comment.content | slice(0, 50) }}
                        {% if comment.content|length >= 51 %}
                            ...
                        {% endif %}
                    </li>
            {% endfor %}
        </ul>
    </div>
{% endblock body %}

templates/user/show_comments.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes réponses{% endblock %}

{% block body %}
    <div class="block mb-20">
        <h3 class="pb-30">Mes réponses</h3>
        <ul>
            {% for comment in app.user.comments %}
                    <li class="pb-30">
                        {{ comment.content|slice(0, 50) }}
                        {% if comment.content|length >= 51 %}
                            ...
                        {% endif %}
                    </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/user/show_questions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes questions{% endblock %}

{% block body %}
    <div class="block mb-20">
        <h3 class="pb-30">Mes questions</h3>
        <ul>
            {% for question in app.user.questions %}
                <a href="{{ path('question_show', {id: question.id}) }}">
                    <li class="pb-30">{{ question.title }}</li>
                </a>
            {% endfor %}
        </ul>
    </div>
{% endblock %}